Repository nephio-project/docs, pull requests merged in 2023-06, with the labels that each got.

#19 Skeleton for release notes, user guide and install guide
  install-guide/install-guide.md
  release-notes/release-notes.md
  user-guide/user-guide.md
Labels: approved, lgtm

#24 Explore sandbox
  .gitignore
  install-guide/ExploreSandbox-diagrams/ManagementCluster.drawio
  install-guide/ExploreSandbox-diagrams/ManagementCluster.png
  install-guide/ExploreSandbox-diagrams/SandboxRepos.drawio
  install-guide/ExploreSandbox.md
  learning.md
Labels: approved, lgtm

#25 Fix typo (case sensitive OS)
  install-guide/ExploreSandbox.md
Labels: approved, lgtm

#20 Windows demo documentation
  install-guide/demo-vagrant-windows.md
Labels: approved, lgtm

#21 Started draft for user guide
  .gitignore
  user-guide/nephio-deployment.png
  user-guide/nephio-overview.png
  user-guide/package-ancestry.png
  user-guide/package-lifecycle.png
  user-guide/user-guide.md
Labels: approved, lgtm

#22 Started the draft for release notes
  release-notes/release-notes.md
Labels: approved, lgtm

#23 Add Nephio R1 diagram
  user-guide/nephio-R1-demo.drawio
  user-guide/nephio-R1-demo.png
Labels: approved, lgtm, needs-ok-to-test

#26 Add package transformaiton doc
  install-guide/PackageTransformations.md
Labels: approved, lgtm

#27 Add note on reoncilers in controller
  user-guide/NephioControllerNotes.md
Labels: approved, lgtm

#28 Fix typos and improve natural language linting issues
  .gitignore
  .spellcheck.yml
  .textlintrc
  .wordlist.txt
  Makefile
  README.md
  abbreviations.md
  glossary.md
  install-guide/ExploreSandbox.md
  install-guide/PackageTransformations.md
  learning.md
  release-notes/release-notes.md
  tox.ini
  user-guide/user-guide.md
Labels: approved, lgtm

#29 Basic updates to docs, overview
  README.md
  install-guide/PackageTransformations.md
  install-guide/README.md
  release-notes/README.md
  release-notes/release-notes.md
  resources.md
  user-guide/README.md
  user-guide/user-guide.md
Labels: approved

#34 First Pass on Syntax and Grammar Edits
  README.md
  glossary.md
  install-guide/README.md
  install-guide/demo-vagrant-windows.md
  install-guide/explore-sandbox.md
  install-guide/package-transformations.md
  learning.md
  release-notes/README.md
  resources.md
  user-guide/README.md
  user-guide/controllers.md
  user-guide/exercises.md
Labels: approved, lgtm

#35 Workload transf
  install-guide/package-transformations.md
Labels: approved, lgtm
