Repository nephio-project/docs, pull requests merged in 2023-11, with the labels that each got.

#62 updates the environment variables table to login to dockerhub
  install-guide/README.md
Labels: approved, lgtm

#69 Minimal install
  README.md
  developer-guide/README.md
  developer-guide/minimal-environment.md
  learning.md
Labels: approved, lgtm

#65 Add DOCKER_REGISTRY_MIRRORS environment variable to install script docs
  install-guide/README.md
Labels: approved, lgtm

#68 Initial documentation for OpenShift
  install-guide/openshift.md
Labels: approved, lgtm, ok-to-test

#64 Update GCP instructions to use CC
  install-guide/gcp-console-packages.png
  install-guide/gcp.md
  install-guide/nephio-login.png
  install-guide/webui-auth-gcp.md
Labels: approved

#70 Documentation Openstack
  install-guide/openstack.md
Labels: approved, lgtm

#71 Some corrections to the GCP instructions
  install-guide/gcp.md
  install-guide/img/gcp/gcp-console-packages.png
  install-guide/img/gcp/nephio-login.png
Labels: approved, lgtm

#74 Fix Natural language issues and typos
  .wordlist.txt
  developer-guide/minimal-environment.md
  install-guide/byoc.md
  install-guide/gcp.md
  install-guide/openshift.md
  install-guide/openstack.md
  install-guide/sandbox.md
  install-guide/webui.md
Labels: approved, lgtm
