Repository nephio-project/docs, pull requests merged in 2024-01, with the labels that each got.

#79 Update gitignore to exclude build data
  .gitignore
Labels: approved, lgtm

#78 Add efiacor to OWNERS reviewers section
  OWNERS
Labels: approved, lgtm

#80 Fix broken hyperlinks
  README.md
  content/en/docs/guides/install-guides/_index.md
  content/en/docs/guides/install-guides/package-transformations.md
  content/en/docs/guides/user-guides/_index.md
Labels: approved, lgtm

#86 Update some broken links of docs
  README.md
Labels: approved, lgtm, ok-to-test

#92 Change owners
  OWNERS
  developer-guide/README.md
Labels: approved, lgtm

#81 Update openstack documentation
  content/en/docs/guides/install-guides/openstack.md
Labels: approved, lgtm

#83 Adding footer with Code of Conduct and Netlify
  config.toml
  content/en/_index.md
  layouts/partials/footer.html
Labels: approved, lgtm, ok-to-test

#94 Add efiacor to approvers section
  OWNERS
Labels: approved, lgtm

#96 Fixing typo in the footer
  layouts/partials/footer.html
Labels: approved, lgtm, needs-ok-to-test

#93 Revert inadvertent check in of file to documentation
  developer-guide/README.md
Labels: approved, lgtm

#85 Updating docs for R2
  content/en/docs/guides/install-guides/install-on-gce.md
  content/en/docs/guides/user-guides/exercise-1-free5gc.md
  content/en/docs/guides/user-guides/exercise-2-oai.md
  static/images/user-guides/nephio-r2-5g-network.png
  static/images/user-guides/nephio-r2-deployment-diagram.png
Labels: approved, lgtm

#91 Add linkcheck GitHub workflow
  .github/workflows/check-links-md.yml
  .linkspector.yml
Labels: approved, lgtm, ok-to-test

#98 Remove documentation typos
  .wordlist.txt
  content/en/_index.md
  content/en/docs/guides/install-guides/install-on-gce.md
  content/en/docs/guides/install-guides/install-on-openshift.md
  content/en/docs/guides/install-guides/webui-auth-gcp.md
  content/en/docs/guides/install-guides/webui-auth-okta.md
  content/en/docs/guides/user-guides/exercise-2-oai.md
Labels: approved, lgtm

#99 Fix exercise links
  content/en/docs/guides/install-guides/_index.md
  content/en/docs/guides/install-guides/install-on-gcp.md
  content/en/docs/guides/user-guides/helm/flux-helm.md
Labels: approved, lgtm

#77 Adding Controller user's guide
  content/en/docs/guides/user-guides/controllers.md
Labels: approved, lgtm, ok-to-test

#88 Common dependencies
  content/en/docs/guides/install-guides/common-components.md
  content/en/docs/guides/install-guides/common-dependencies.md
Labels: approved, lgtm

#97 Update the guide for deploying a Minimal develpoment environment
  content/en/docs/guides/contributor-guides/minimal-environment.md
Labels: approved, lgtm
