Repository nephio-project/docs, pull requests merged in 2024-04, with the labels that each got.

#123 updated doc to call out docker supplementary group is loaded
  content/en/docs/guides/user-guides/exercise-1-free5gc.md
  content/en/docs/guides/user-guides/exercise-2-oai.md
Labels: approved, lgtm

#124 Architecture
  content/en/docs/architecture.md
  diagrams/src/level1-nephio-system.puml
  diagrams/src/level2-nephio-container.puml
  diagrams/src/level3-nephio-core-component.puml
  diagrams/src/level3-nephio-porch-component.puml
  static/images/architecture/level1-nephio-system.png
  static/images/architecture/level2-nephio-container.png
  static/images/architecture/level3-nephio-core-component.png
  static/images/architecture/nephio-porch-component-view.png
Labels: approved, lgtm

#125 Fix incorrect base URL
  .gitignore
  config.toml
Labels: documentation, approved, lgtm

#122 Update install-on-multiple-vm.md
  content/en/docs/guides/install-guides/install-on-multiple-vm.md
Labels: approved, lgtm, needs-ok-to-test

#120 License update to CC-BY-4.0
  .spellcheck.yml
  LICENSE
  Makefile
Labels: approved, lgtm, ok-to-test
