Repository nephio-project/docs, pull requests merged in 2024-12, with the labels that each got.

#192 Updates to documentation for Porch
  content/en/docs/porch/config-as-data.md
  content/en/docs/porch/package-orchestration.md
Labels: approved, lgtm

#193 Improve doc site navigation
  config.toml
  layouts/_default/_markup/render-heading.html
Labels: approved, lgtm

#195 Fix invalid @@ pkg urls
  content/en/docs/guides/install-guides/common-dependencies.md
  content/en/docs/guides/install-guides/install-on-multiple-vm.md
  content/en/docs/guides/install-guides/install-on-single-vm.md
Labels: bug, documentation, approved, lgtm

#197 Add missing APIs to be enabled in the documentation
  content/en/docs/guides/install-guides/install-on-gcp.md
Labels: approved, lgtm

#194 Language corrections for install guides.
  content/en/docs/guides/install-guides/_index.md
Labels: approved, lgtm, ok-to-test

#196 Clean up porch guides
  .github/workflows/check-links-md.yml
  content/en/docs/guides/install-guides/install-on-byoc.md
  content/en/docs/guides/install-guides/install-on-multiple-vm.md
  content/en/docs/porch/_index.md
  content/en/docs/porch/contributors-guide/environment-setup-vm.md
  content/en/docs/porch/contributors-guide/environment-setup.md
  content/en/docs/porch/package-orchestration.md
  content/en/docs/porch/running-porch/running-on-GKE.md
  content/en/docs/porch/user-guides/_index.md
  content/en/docs/porch/user-guides/adding-external-git-ca-bundle.md
  content/en/docs/porch/user-guides/install-and-using-porch.md
  content/en/docs/porch/user-guides/porchctl-cli-guide.md
  content/en/docs/porch/user-guides/using-authenticated-private-registries.md
  content/en/docs/porch/using-porch/porchctl-cli-guide.md
Labels: documentation, approved, lgtm

#198 Adding more exceptions to the allow list
  .vale/config/vocabularies/Nephio/accept.txt
Labels: approved, lgtm
