Repository nephio-project/docs, pull requests merged in 2024-11, with the labels that each got.

#175 Language corrections for the R3 Release Notes.
  content/en/docs/release-notes/R3.md
Labels: approved, lgtm, ok-to-test

#178 Adding Porch private authenticated registries functionality documentation
  content/en/docs/porch/using-porch/using-authenticated-private-registries.md
Labels: approved, lgtm

#181 Instructions on Porch Tracing setup added to Porch contributor guide
  content/en/docs/porch/contributors-guide/environment-setup.md
Labels: approved, lgtm

#184 Making vale optional
  .github/workflows/proofreading-vale.yml
Labels: approved, lgtm

#179 Correcting identifiers
  .linkspector.yml
  content/en/docs/_index.md
  content/en/docs/guides/contributor-guides/helm-to-operator-codegen-sdk-developer-guide.md
  content/en/docs/guides/contributor-guides/minimal-environment.md
  content/en/docs/guides/contributor-guides/unit-testing-mockery.md
  content/en/docs/guides/install-guides/_index.md
  content/en/docs/guides/install-guides/common-components.md
  content/en/docs/guides/install-guides/common-dependencies.md
  content/en/docs/guides/install-guides/demo-vagrant-windows.md
  content/en/docs/guides/install-guides/explore-nephio-free5gc.md
  content/en/docs/guides/install-guides/explore-sandbox.md
  content/en/docs/guides/install-guides/install-on-byoc.md
  content/en/docs/guides/install-guides/install-on-gce.md
  content/en/docs/guides/install-guides/install-on-gcp.md
  content/en/docs/guides/install-guides/install-on-multiple-vm.md
  content/en/docs/guides/install-guides/install-on-openshift.md
  content/en/docs/guides/install-guides/install-on-single-vm.md
  content/en/docs/guides/install-guides/package-transformations.md
  content/en/docs/guides/install-guides/webui-auth-gcp.md
  content/en/docs/guides/install-guides/webui-auth-okta.md
  content/en/docs/guides/install-guides/webui.md
  content/en/docs/guides/user-guides/controllers.md
  content/en/docs/guides/user-guides/exercise-1-free5gc.md
  content/en/docs/guides/user-guides/exercise-2-oai.md
  content/en/docs/guides/user-guides/helm/flux-helm.md
  content/en/docs/guides/user-guides/helm/helm-to-operator-codegen-sdk-user-guide.md
  content/en/docs/network-architecture/o-ran-integration.md
  content/en/docs/porch/config-as-data.md
  content/en/docs/porch/contributors-guide/_index.md
  content/en/docs/porch/contributors-guide/dev-process.md
  content/en/docs/porch/contributors-guide/environment-setup-vm.md
  content/en/docs/porch/contributors-guide/environment-setup.md
  content/en/docs/porch/package-orchestration.md
  content/en/docs/porch/package-variant.md
  content/en/docs/porch/running-porch/running-locally.md
  content/en/docs/porch/running-porch/running-on-GKE.md
  content/en/docs/porch/using-porch/adding-external-git-ca-bundle.md
  content/en/docs/porch/using-porch/install-and-using-porch.md
  content/en/docs/porch/using-porch/porchctl-cli-guide.md
  content/en/docs/porch/using-porch/usage-porch-kpt-cli.md
Labels: approved, lgtm

#176 Fixing some of the linting errors
  .github/workflows/proofreading-vale.yml
  .vale.ini
  .vale/config/vocabularies/Nephio/accept.txt
  README.md
  content/en/docs/apis/_index.md
  content/en/docs/architecture.md
  content/en/docs/glossary.md
  content/en/docs/guides/_index.md
  content/en/docs/guides/contributor-guides/documentation.md
  content/en/docs/guides/contributor-guides/minimal-environment.md
  content/en/docs/guides/contributor-guides/unit-testing-mockery.md
  content/en/docs/guides/install-guides/_index.md
  content/en/docs/guides/install-guides/common-components.md
  content/en/docs/guides/install-guides/common-dependencies.md
  content/en/docs/guides/install-guides/demo-vagrant-windows.md
  content/en/docs/guides/install-guides/explore-nephio-free5gc.md
  content/en/docs/guides/install-guides/explore-sandbox.md
  content/en/docs/guides/install-guides/install-on-byoc.md
  content/en/docs/guides/install-guides/install-on-gcp.md
  content/en/docs/guides/install-guides/install-on-multiple-vm.md
  content/en/docs/guides/install-guides/install-on-openshift.md
  content/en/docs/guides/install-guides/install-on-single-vm.md
  content/en/docs/guides/install-guides/package-transformations.md
  content/en/docs/guides/install-guides/webui-auth-gcp.md
  content/en/docs/guides/install-guides/webui-auth-okta.md
  content/en/docs/guides/install-guides/webui.md
  content/en/docs/guides/user-guides/_index.md
  content/en/docs/guides/user-guides/controllers.md
  content/en/docs/guides/user-guides/exercise-1-free5gc.md
  content/en/docs/guides/user-guides/exercise-2-oai.md
  content/en/docs/guides/user-guides/helm/_index.md
  content/en/docs/guides/user-guides/helm/flux-helm.md
  content/en/docs/guides/user-guides/helm/helm-to-operator-codegen-sdk-user-guide.md
  content/en/docs/porch/_index.md
  content/en/docs/porch/contributors-guide/_index.md
  content/en/docs/porch/contributors-guide/dev-process.md
  content/en/docs/porch/contributors-guide/environment-setup-vm.md
  content/en/docs/porch/contributors-guide/environment-setup.md
  content/en/docs/porch/package-orchestration.md
  content/en/docs/porch/running-porch/running-on-GKE.md
  content/en/docs/porch/using-porch/adding-external-git-ca-bundle.md
  content/en/docs/porch/using-porch/install-and-using-porch.md
  content/en/docs/porch/using-porch/porchctl-cli-guide.md
  content/en/docs/porch/using-porch/usage-porch-kpt-cli.md
  content/en/docs/release-notes/R1.md
  content/en/docs/release-notes/R2.md
Labels: approved, lgtm

#180 Models and apis language corrections
  content/en/docs/apis/_index.md
Labels: approved, lgtm, needs-ok-to-test

#182 Remove Function CR refs
  content/en/docs/porch/contributors-guide/_index.md
  content/en/docs/porch/contributors-guide/dev-process.md
  content/en/docs/porch/contributors-guide/environment-setup.md
  content/en/docs/porch/package-orchestration.md
  content/en/docs/porch/running-porch/running-locally.md
  content/en/docs/porch/running-porch/running-on-GKE.md
  content/en/docs/porch/using-porch/install-and-using-porch.md
  content/en/docs/porch/using-porch/usage-porch-kpt-cli.md
Labels: approved, lgtm

#183 Adding documentation for TLS registries configuration
  content/en/docs/porch/using-porch/using-authenticated-private-registries.md
Labels: approved, lgtm

#188 Adding exceptions to the vale accept file
  .vale/config/vocabularies/Nephio/accept.txt
Labels: approved, lgtm

#185 Added documentation for the load test script
  content/en/docs/porch/contributors-guide/dev-process.md
Labels: approved, lgtm

#189 Rephrase text on Porch main document page
  content/en/docs/porch/_index.md
Labels: approved, lgtm
