Repository nephio-project/docs, pull requests merged in 2025-02, with the labels that each got.

#203 Add usecase guide for Centralized FluxCD deployment
  .linkspector.yml
  content/en/docs/guides/install-guides/_index.md
  content/en/docs/guides/install-guides/common-components.md
  content/en/docs/guides/install-guides/install-on-byoc.md
  content/en/docs/guides/install-guides/install-on-gce.md
  content/en/docs/guides/install-guides/install-on-gcp.md
  content/en/docs/guides/install-guides/optional-components.md
  content/en/docs/guides/user-guides/_index.md
  content/en/docs/guides/user-guides/helm/_index.md
  content/en/docs/guides/user-guides/helm/flux-helm.md
  content/en/docs/guides/user-guides/operator-controller-guides/_index.md
  content/en/docs/guides/user-guides/operator-controller-guides/controllers.md
  content/en/docs/guides/user-guides/usecase-user-guides/_index.md
  content/en/docs/guides/user-guides/usecase-user-guides/exercise-1-free5gc.md
  content/en/docs/guides/user-guides/usecase-user-guides/exercise-2-oai.md
  content/en/docs/guides/user-guides/usecase-user-guides/exercise-3-fluxcd-wl.md
  content/en/docs/porch/running-porch/running-on-GKE.md
  content/en/docs/porch/user-guides/porchctl-cli-guide.md
Labels: approved, lgtm

#209 add usecase user guides for the o2ims operator
  content/en/docs/guides/install-guides/optional-components.md
  content/en/docs/guides/user-guides/usecase-user-guides/exercise-4-o2ims.md
Labels: approved, lgtm

#206 Update documentation.md
  content/en/docs/guides/contributor-guides/documentation.md
Labels: approved, lgtm

#207 Address missed comments from PR #203
  content/en/docs/guides/install-guides/optional-components.md
  content/en/docs/guides/user-guides/usecase-user-guides/exercise-3-fluxcd-wl.md
Labels: documentation, approved, lgtm

#211 Update oran focom docs
  content/en/docs/network-architecture/o-ran-integration.md
  static/images/network-architecture/o-ran/focom1.png
  static/images/network-architecture/o-ran/focom2.png
  static/images/network-architecture/o-ran/ims-provisioning-create-cluster.png
Labels: documentation, approved, lgtm

#210 Release notes for R4
  content/en/docs/release-notes/R4.md
Labels: approved, lgtm

#212 Update R4 dropdown item and api refs
  config.toml
  content/en/docs/apis/porch/_index.md
  content/en/docs/apis/topology-and-networking/_index.md
Labels: documentation, approved, lgtm

#213 Update R4 dropdown item and api refs (#212)
  config.toml
  content/en/docs/apis/porch/_index.md
  content/en/docs/apis/topology-and-networking/_index.md
Labels: documentation, approved, lgtm

#214 Fix dropdown menu links
  config.toml
  package.json
Labels: documentation, approved, lgtm

#215 Fix release dropdown menu
  .github/workflows/check-links-md.yml
  .linkspector.yml
  config.toml
  content/en/docs/porch/contribturos-guide/_index.md
  content/en/docs/porch/package-orchestration.md
Labels: documentation, approved, lgtm

#205 Updated docs to remove mention of mutators/validators against Repository from Porch Orchestration page
  content/en/docs/porch/contributors-guide/_index.md
  content/en/docs/porch/package-orchestration.md
Labels: approved, lgtm, needs-ok-to-test
